//
// Created by Bugen Zhao on 2019/12/7.
//

#ifndef FINALPROJECT_HINT_HPP
#define FINALPROJECT_HINT_HPP

#include <QString>

namespace BugenZhao {
    QString hintRichText = "<html>\n"
                           "\n"
                           "<head />\n"
                           "\n"
                           "<body>\n"
                           "    <table border=\"0\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" align=\"center\"\n"
                           "        cellspacing=\"2\" cellpadding=\"0\">\n"
                           "        <tr>\n"
                           "            <td>\n"
                           "                <p><span style=\" font-size:24pt; font-weight:600; color:#6c6c6c;\">⌘,</span></p>\n"
                           "            </td>\n"
                           "            <td>\n"
                           "                <p><span style=\" font-size:24pt; font-weight:600; color:#6c6c6c;\">: Application</span><span\n"
                           "                        style=\" font-size:24pt; color:#6c6c6c;\"> ➡️ Preferences...</span></p>\n"
                           "            </td>\n"
                           "        </tr>\n"
                           "        <tr>\n"
                           "            <td>\n"
                           "                <p><span style=\" font-size:24pt; font-weight:600; color:#6c6c6c;\">⌘O</span></p>\n"
                           "            </td>\n"
                           "            <td>\n"
                           "                <p><span style=\" font-size:24pt; font-weight:600; color:#6c6c6c;\">: File</span><span\n"
                           "                        style=\" font-size:24pt; color:#6c6c6c;\"> ➡️ Open data set folder...</span></p>\n"
                           "            </td>\n"
                           "        </tr>\n"
                           "        <tr>\n"
                           "            <td>\n"
                           "                <p><span style=\" font-size:24pt; font-weight:600; color:#6c6c6c;\">⌘⏎</span></p>\n"
                           "            </td>\n"
                           "            <td>\n"
                           "                <p><span style=\" font-size:24pt; font-weight:600; color:#6c6c6c;\">: File</span><span\n"
                           "                        style=\" font-size:24pt; color:#6c6c6c;\"> ➡️ Apply Importer &amp; Filters</span></p>\n"
                           "            </td>\n"
                           "        </tr>\n"
                           "        <tr>\n"
                           "            <td>\n"
                           "                <p><span style=\" font-size:24pt; font-weight:600; color:#6c6c6c;\">⌘1</span></p>\n"
                           "            </td>\n"
                           "            <td>\n"
                           "                <p><span style=\" font-size:24pt; font-weight:600; color:#6c6c6c;\">: Window </span><span\n"
                           "                        style=\" font-size:24pt; color:#6c6c6c;\">➡️ Add tab... </span>"
                           "<span style=\" font-size:24pt; color:#6c6c6c;\">➡️ Inflow and outflow plot</span></p>\n"
                           "            </td>\n"
                           "        </tr>\n"
                           "        <tr>\n"
                           "            <td>\n"
                           "                <p><span style=\" font-size:24pt; font-weight:600; color:#6c6c6c;\">⌘2</span></p>\n"
                           "            </td>\n"
                           "            <td>\n"
                           "                <p><span style=\" font-size:24pt; font-weight:600; color:#6c6c6c;\">: Window </span><span\n"
                           "                        style=\" font-size:24pt; color:#6c6c6c;\">➡️ Add tab... </span>"
                           "<span style=\" font-size:24pt; color:#6c6c6c;\">➡️ Total flow plot</span></p>\n"
                           "            </td>\n"
                           "        </tr>\n"
                           "        <tr>\n"
                           "            <td>\n"
                           "                <p><span style=\" font-size:24pt; font-weight:600; color:#6c6c6c;\">⌘3</span></p>\n"
                           "            </td>\n"
                           "            <td>\n"
                           "                <p><span style=\" font-size:24pt; font-weight:600; color:#6c6c6c;\">: Window </span><span\n"
                           "                        style=\" font-size:24pt; color:#6c6c6c;\">➡️ Add tab... </span>"
                           "<span style=\" font-size:24pt; color:#6c6c6c;\">➡️ Inflow plot with lines</span></p>\n"
                           "            </td>\n"
                           "        </tr>\n"
                           "        <tr>\n"
                           "            <td>\n"
                           "                <p><span style=\" font-size:24pt; font-weight:600; color:#6c6c6c;\">⌘I</span></p>\n"
                           "            </td>\n"
                           "            <td>\n"
                           "                <p><span style=\" font-size:24pt; font-weight:600; color:#6c6c6c;\">: Window</span><span\n"
                           "                        style=\" font-size:24pt; color:#6c6c6c;\"> ➡️ Importer &amp; Filters</span></p>\n"
                           "            </td>\n"
                           "        </tr>\n"
                           "    </table>\n"
                           "</body>\n"
                           "\n"
                           "</html>";
}

#endif //FINALPROJECT_HINT_HPP
